### ISSUE TITLE
Fast Fail Exception instantly

### ISSUE THREAD

**Issue by Kyouki-DotExe** [wabbajack-tools/wabbajack#2790]
**Describe the bug**

The bug occurs when you're on a slightly older or outdated Windows 10 instance (guessing) and with .net9 developed applications want to run but require CFG or ShadowStack(?) Windows Defender stuff. 
It errors instantly towards Fail Fast Exception. (see attached) which causes it not to be able to be run.

![Image](https://github.com/user-attachments/assets/7b358e1c-b95e-43f8-9129-f4cdd87077f8)

**Additional Context**

Windows 10

**Wabbajack Version**

Latest

**Logs**

No logs generated due to not even starting as expected.

Additional information would be that I went through this with another application (and more) and managed fix it by including a line in cetcompat: https://github.com/beeradmoore/dlss-swapper/issues/328

**Comment by Mieekaserra** [comment]
This is not a bug, Wabbajack requires 22H2 service pack installed, build 19045.5198 or newer. Older versions of windows 10 are not supported.

You are running a LTSC version which cannot update to 22H2.

**Comment by Mieekaserra** [comment]
It can also be resolved by you using an OS which has been updated in the last 5 years and doesnt have more holes than a block of swiss cheese.

the fact that you are using LTSC windows on the internet which has no security updates since 2021 is frankly terrifying.

**Comment by Mieekaserra** [comment]
Not by us.

**Comment by JanuarySnow** [comment]
Nobody on the dev team has older versions of WIndows I believe, and setting up a VM or something for what would be a low priority issue is not really that compelling.

If however you wanted to test this change with your own compiled version of WJ and report back as to whether it breaks anything else, that would be useful.

**Comment by tr4wzified** [comment]
Agreed with the others here. Contrary to what others have said, LTSC still receives updates and is fine to run. You're just missing out on feature updates and things like these. However I don't think turning off .NET security features should be a default setting considering this isn't a typical consumer setup.

I'm reading here there's a way to override it per application with a group policy without reinstalling the OS, on this page at the bottom. Maybe that helps you: https://learn.microsoft.com/en-us/dotnet/core/compatibility/interop/9.0/cet-support
